#Importing required libraries

In [2]:
import numpy as np
import pandas as pd

#below command fetches datasets from scikit site


In [ ]:
from sklearn import datasets 
from sklearn.model_selection import train_test_split

#Loading Dataset into variable IRIS


In [4]:
IRIS = datasets.load_iris()

{'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ===========

# Content Stored in Variable IRIS is displayed

In [5]:
IRIS

{'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ===========

# We want to view data separately

In [6]:
x=IRIS.data
y=IRIS.target

#Output of x and y

In [8]:
print("Input Data",x)

Input Data [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 

##Output of y i.e Target variable

In [9]:
print("Target Data",y)

Target Data [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


#creating Data Frame

In [11]:
df = pd.DataFrame(data=np.c_[IRIS['data'],IRIS['target']],columns=IRIS['feature_names']+['Species'])
df

sepal length (cm)  sepal width (cm)  ...  petal width (cm)  Species
0                  5.1               3.5  ...               0.2      0.0
1                  4.9               3.0  ...               0.2      0.0
2                  4.7               3.2  ...               0.2      0.0
3                  4.6               3.1  ...               0.2      0.0
4                  5.0               3.6  ...               0.2      0.0
..                 ...               ...  ...               ...      ...
145                6.7               3.0  ...               2.3      2.0
146                6.3               2.5  ...               1.9      2.0
147                6.5               3.0  ...               2.0      2.0
148                6.2               3.4  ...               2.3      2.0
149                5.9               3.0  ...               1.8      2.0

[150 rows x 5 columns]

#To Know dataset mean,std,min,max

In [12]:
df.describe()

sepal length (cm)  sepal width (cm)  ...  petal width (cm)     Species
count         150.000000        150.000000  ...        150.000000  150.000000
mean            5.843333          3.057333  ...          1.199333    1.000000
std             0.828066          0.435866  ...          0.762238    0.819232
min             4.300000          2.000000  ...          0.100000    0.000000
25%             5.100000          2.800000  ...          0.300000    0.000000
50%             5.800000          3.000000  ...          1.300000    1.000000
75%             6.400000          3.300000  ...          1.800000    2.000000
max             7.900000          4.400000  ...          2.500000    2.000000

[8 rows x 5 columns]

# Splitting Training and Testing dataset

In [13]:
from sklearn.model_selection import train_test_split

In [23]:
# Here test data is of 30% by test_size=0.3 which is in probability and set random state as any number to just fix no of dataset in both
df_train,df_test = train_test_split(df, test_size=0.3, random_state=25)


In [24]:
# Here you can see data is randomly separated for training and testing
# Print Train Data
df_train

sepal length (cm)  sepal width (cm)  ...  petal width (cm)  Species
10                 5.4               3.7  ...               0.2      0.0
33                 5.5               4.2  ...               0.2      0.0
78                 6.0               2.9  ...               1.5      1.0
27                 5.2               3.5  ...               0.2      0.0
121                5.6               2.8  ...               2.0      2.0
..                 ...               ...  ...               ...      ...
118                7.7               2.6  ...               2.3      2.0
61                 5.9               3.0  ...               1.5      1.0
143                6.8               3.2  ...               2.3      2.0
62                 6.0               2.2  ...               1.0      1.0
132                6.4               2.8  ...               2.2      2.0

[105 rows x 5 columns]

In [22]:
# Print Test Data
df_test

sepal length (cm)  sepal width (cm)  ...  petal width (cm)  Species
28                 5.2               3.4  ...               0.2      0.0
72                 6.3               2.5  ...               1.5      1.0
70                 5.9               3.2  ...               1.8      1.0
85                 6.0               3.4  ...               1.6      1.0
128                6.4               2.8  ...               2.1      2.0
65                 6.7               3.1  ...               1.4      1.0
127                6.1               3.0  ...               1.8      2.0
42                 4.4               3.2  ...               0.2      0.0
81                 5.5               2.4  ...               1.0      1.0
93                 5.0               2.3  ...               1.0      1.0
21                 5.1               3.7  ...               0.4      0.0
31                 5.4               3.4  ...               0.4      0.0
26                 5.0               3.4  ...               0.4      0.0
133                6.3               2.8  ...               1.5      2.0
6                  4.6               3.4  ...               0.3      0.0
58                 6.6               2.9  ...               1.3      1.0
125                7.2               3.2  ...               1.8      2.0
139                6.9               3.1  ...               2.1      2.0
64                 5.6               2.9  ...               1.3      1.0
94                 5.6               2.7  ...               1.3      1.0
79                 5.7               2.6  ...               1.0      1.0
99                 5.7               2.8  ...               1.3      1.0
66                 5.6               3.0  ...               1.5      1.0
20                 5.4               3.4  ...               0.2      0.0
34                 4.9               3.1  ...               0.2      0.0
117                7.7               3.8  ...               2.2      2.0
69                 5.6               2.5  ...               1.1      1.0
122                7.7               2.8  ...               2.0      2.0
120                6.9               3.2  ...               2.3      2.0
41                 4.5               2.3  ...               0.3      0.0
54                 6.5               2.8  ...               1.5      1.0
113                5.7               2.5  ...               2.0      2.0
135                7.7               3.0  ...               2.3      2.0
4                  5.0               3.6  ...               0.2      0.0
115                6.4               3.2  ...               2.3      2.0
52                 6.9               3.1  ...               1.5      1.0
68                 6.2               2.2  ...               1.5      1.0
40                 5.0               3.5  ...               0.3      0.0
23                 5.1               3.3  ...               0.5      0.0
35                 5.0               3.2  ...               0.2      0.0
16                 5.4               3.9  ...               0.4      0.0
0                  5.1               3.5  ...               0.2      0.0
8                  4.4               2.9  ...               0.2      0.0
25                 5.0               3.0  ...               0.2      0.0
138                6.0               3.0  ...               1.8      2.0

[45 rows x 5 columns]

####Q- Import California house dataset from scikit learn and separate train and test dataset

In [27]:
from sklearn import datasets

cal_house = datasets.fetch_california_housing()
cal_house

{'DESCR': '.. _california_housing_dataset:\n\nCalifornia Housing dataset\n--------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 20640\n\n    :Number of Attributes: 8 numeric, predictive attributes and the target\n\n    :Attribute Information:\n        - MedInc        median income in block group\n        - HouseAge      median house age in block group\n        - AveRooms      average number of rooms per household\n        - AveBedrms     average number of bedrooms per household\n        - Population    block group population\n        - AveOccup      average number of household members\n        - Latitude      block group latitude\n        - Longitude     block group longitude\n\n    :Missing Attribute Values: None\n\nThis dataset was obtained from the StatLib repository.\nhttps://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html\n\nThe target variable is the median house value for California districts,\nexpressed in hundreds of thousands of dollars

###creating dataframes

######df = pd.DataFrame(data=np.c_[IRIS['data'],IRIS['target']],columns=IRIS['feature_names']+['Species'])
df

In [32]:
df2 = pd.DataFrame(data=np.c_[cal_house['data'],cal_house['target']],columns=cal_house['feature_names'] + cal_house['target_names'] )
df2

MedInc  HouseAge  AveRooms  ...  Latitude  Longitude  MedHouseVal
0      8.3252      41.0  6.984127  ...     37.88    -122.23        4.526
1      8.3014      21.0  6.238137  ...     37.86    -122.22        3.585
2      7.2574      52.0  8.288136  ...     37.85    -122.24        3.521
3      5.6431      52.0  5.817352  ...     37.85    -122.25        3.413
4      3.8462      52.0  6.281853  ...     37.85    -122.25        3.422
...       ...       ...       ...  ...       ...        ...          ...
20635  1.5603      25.0  5.045455  ...     39.48    -121.09        0.781
20636  2.5568      18.0  6.114035  ...     39.49    -121.21        0.771
20637  1.7000      17.0  5.205543  ...     39.43    -121.22        0.923
20638  1.8672      18.0  5.329513  ...     39.43    -121.32        0.847
20639  2.3886      16.0  5.254717  ...     39.37    -121.24        0.894

[20640 rows x 9 columns]

In [33]:
from sklearn.model_selection import train_test_split
df2_train, df2_test = train_test_split(df2,test_size=0.3,random_state=25)


In [34]:
#Train dataset
df2_train.head()

MedInc  HouseAge  AveRooms  ...  Latitude  Longitude  MedHouseVal
8275    2.1270      15.0  3.958746  ...     33.78    -118.16      1.63300
10148   9.5561      27.0  8.094937  ...     33.91    -117.92      4.11800
6720   10.7397      46.0  7.460993  ...     34.12    -118.13      5.00001
18039   7.8407      36.0  7.274671  ...     37.23    -121.96      4.76400
15532   3.7109      11.0  5.717526  ...     33.18    -117.14      1.99800

[5 rows x 9 columns]

In [35]:
#test dataset
df2_test.head()

MedInc  HouseAge  AveRooms  ...  Latitude  Longitude  MedHouseVal
73     0.4999      46.0  1.714286  ...     37.81    -122.29        0.675
8944   2.9167      43.0  4.640000  ...     34.01    -118.47        4.611
3737   3.4013      27.0  4.119403  ...     34.17    -118.40        2.860
19092  6.2040      19.0  6.564202  ...     38.24    -122.62        2.018
9493   3.2500      16.0  4.935484  ...     39.37    -123.75        1.514

[5 rows x 9 columns]

In [37]:
cal_house.target

array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894])

In [38]:
cal_house.target_names

['MedHouseVal']

In [44]:
df2.info() # here you can see datatype of each data 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   MedInc       20640 non-null  float64
 1   HouseAge     20640 non-null  float64
 2   AveRooms     20640 non-null  float64
 3   AveBedrms    20640 non-null  float64
 4   Population   20640 non-null  float64
 5   AveOccup     20640 non-null  float64
 6   Latitude     20640 non-null  float64
 7   Longitude    20640 non-null  float64
 8   MedHouseVal  20640 non-null  float64
dtypes: float64(9)
memory usage: 1.4 MB
